### ISSUE TITLE
Cache pipeline

### ISSUE THREAD

**Issue by irgolic** [irgolic/stable-diffusion-api#22]
One of the perks of using an all-in-one `stable_diffusion_mega` pipeline is that we can cache it between runs, so it doesn't initialize on every task.

A low-hanging-fruit way to take advantage of this is to make workers cache the last pipeline/model they ran in `runner_service`. Should we come to a point where we're running multiple workers with multiple concurrent pipelines and models, we should give `task_service` ability to keep track of which pipelines are cached by which worker.

**Comment by MicahZoltu** [comment]
You can also cache if using the long prompt weight one can't you?

**Comment by irgolic** [comment]
> You can also cache if using the long prompt weight one can't you?

Correct.

**Comment by irgolic** [comment]
Closed by #28.
